import { IUser, IAuthToken } from './auth_schema';

export const validateUserCredentials = (user: IUser, password: string): boolean => {
  return !!user.id && !!user.passwordHash && !!password;
};

export const generateAuthToken = (userId: string, expiresIn: number): IAuthToken => {
  return {
    token: '', // Will be generated by JWT service
    expiresAt: Date.now() + expiresIn * 1000,
    userId
  };
};

export const isTokenExpired = (expiresAt: number): boolean => {
  return Date.now() > expiresAt;
};
